name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Generate apk
    runs-on: ubuntu-latestp

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello, world! ${{ secrets.TEMP_TESTING }}
